# Generated by Django 6.0.4 on 2026-04-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Electronics", "Electronics"),
                    ("Office", "Office"),
                    ("Accessories", "Accessories"),
                    ("Kitchen", "Kitchen"),
                ],
                default="Electronics",
                max_length=50,
            ),
        ),
    ]
