# Generated by Django 6.0.4 on 2026-04-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_coupon"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "store_name",
                    models.CharField(default="FlashCart Pro", max_length=100),
                ),
                (
                    "store_email",
                    models.EmailField(default="info@flashcartpro.com", max_length=254),
                ),
                (
                    "store_phone",
                    models.CharField(default="+254 700 123 456", max_length=20),
                ),
                ("store_address", models.TextField(default="Nairobi, Kenya")),
                ("store_description", models.TextField(blank=True)),
                ("store_logo", models.URLField(blank=True)),
                (
                    "free_shipping_threshold",
                    models.DecimalField(decimal_places=2, default=5000, max_digits=10),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(decimal_places=2, default=299, max_digits=10),
                ),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=16.0, max_digits=5),
                ),
                ("payment_methods", models.JSONField(default=list)),
                ("currency", models.CharField(default="KES", max_length=3)),
                ("order_prefix", models.CharField(default="ORD", max_length=10)),
                ("auto_confirm_order", models.BooleanField(default=False)),
                ("send_order_confirmation", models.BooleanField(default=True)),
                ("send_payment_confirmation", models.BooleanField(default=True)),
                ("send_shipping_update", models.BooleanField(default=True)),
                ("facebook_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Store Settings",
            },
        ),
    ]
