# Generated by Django 6.0.4 on 2026-04-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_order_product_stock_alter_product_category_orderitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={},
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(default="pending", max_length=20),
        ),
    ]
